blank_issues_enabled: true
contact_links:
  - name: Start a discussion
    url: https://github.com/PrestaShop/PrestaShop/discussions/new
    about: We use Discussions to discuss example modules, tutorials, ask questions, and more.